/* EJEMPLOS USOS ALTER TABLE change, modify,rename, add */

ALTER TABLE emp ADD c_id INTEGER;
ALTER TABLE emp MODIFY mgr NUMERIC;
ALTER TABLE emp CHANGE mgr mgr1 NUMERIC;
ALTER TABLE emp RENAME AS empleaditos;
ALTER TABLE empleaditos RENAME AS emp;
ALTER TABLE salgrade MODIFY grade DECIMAL(10,0) NOT NULL;
ALTER TABLE salgrade ADD CONSTRAINT pk_grade PRIMARY KEY(grade);

ALTER TABLE emp ADD CONSTRAINT fk_sal_grade FOREIGN KEY(sal)
REFERENCES salgrade(grade);

ALTER TABLE emp ADD THRIFPLAN NUMERIC(7,2), 
ADD leancode CHAR(1);
/* CREATE INDEX emp_index ON emp(ename) */
ALTER TABLE emp ADD INDEX emp_index(ename);

/* uso de DROP  */
CREATE TABLE T11(
pk NUMERIC PRIMARY KEY,
FK NUMERIC,
C1 NUMERIC,
C2 NUMERIC);

ALTER TABLE T11 DROP PRIMARY KEY;
ALTER TABLE T11 DROP c1;
ALTER TABLE T11 DROP c2;
ALTER TABLE EMP DROP INDEX emp_index;
DROP TABLE T11;


