INSERT INTO vivienda VALUES ('PARACUELLOS', 'PARACUELLOS JARAMA', 'ALONSO TELLEZ', 'ELIPA, 12');
INSERT INTO vivienda VALUES ('VALLECAS', 'PUENTE VALLECAS', 'EZQUERRO TOME', 'MUSAS, 1');
INSERT INTO vivienda VALUES ('PONCE', 'PONCE LEON', 'GONZALEZ LOPEZ', 'PONCEA, 23');
INSERT INTO vivienda VALUES ('TOLEDO', 'PUERTA TOLEDO', 'JUAREZ NORIEGA', 'TOLEDO, 25');
INSERT INTO vivienda VALUES ('BARAJAS', 'BARAJAS PUEBLO', 'PEREZ LOPEZ', 'ELOY, 2');
INSERT INTO vivienda VALUES ('BRASILIA', 'PARQUE BRASILIA', 'TEJERINA RUIZ', 'BRASILIA, 3');
INSERT INTO vivienda VALUES ('PITIS', 'ESTACION PITIS', 'VAZQUEZ LOPEZ', 'PONCE, 46');


INSERT INTO oficio VALUES ('HERRERO', 'HERRAR CABALLOS');
INSERT INTO oficio VALUES ('CONDUCTOR', 'CONDUCTOR DE AUTOBUS');
INSERT INTO oficio VALUES ('LEÑADOR', 'TALAR ARBOLES');
INSERT INTO oficio VALUES ('OBRERO', 'TRABAJAR EN GENERAL');
INSERT INTO oficio VALUES ('LABRADOR', 'CULTIVAR LA TIERRA');
INSERT INTO oficio VALUES ('PICADOR', 'PICAR EN LOS TUNELES DEL METRO');


INSERT INTO empleado VALUES ('ALONSO TELLEZ', 23, 'PARACUELLOS');
INSERT INTO empleado VALUES ('DIAZ JIMENEZ', 18, 'BARAJAS');
INSERT INTO empleado VALUES ('EZQUERRO TOME', 43, 'VALLECAS');
INSERT INTO empleado VALUES ('GONZALEZ ORBEA', 41, 'BARAJAS');
INSERT INTO empleado VALUES ('PEREZ LOPEZ', 21, 'BARAJAS');
INSERT INTO empleado VALUES ('VAZQUEZ LOPEZ', 67, 'PITIS');
INSERT INTO empleado VALUES ('GONZALEZ LOPEZ', 23, 'PONCE');
INSERT INTO empleado VALUES ('JUAREZ NORIEGA', 25, 'TOLEDO');
INSERT INTO empleado VALUES ('TEJERINA RUIZ', 31, 'BRASILIA');
INSERT INTO empleado VALUES ('ALVAREZ RODRIGUEZ', 23, 'PARACUELLOS');
INSERT INTO empleado VALUES ('DONOSO ANTON', 18, 'BARAJAS');
INSERT INTO empleado VALUES ('EGUIBAR PUENTE', 43, 'VALLECAS');
INSERT INTO empleado VALUES ('GOMEZ ORDUÑA', 41, 'BARAJAS');
INSERT INTO empleado VALUES ('PAVON LOPEZ', 21, 'BARAJAS');
INSERT INTO empleado VALUES ('PANADERO JUAN', 21, 'BARAJAS');


INSERT INTO oficioempleado VALUES ('ALONSO TELLEZ' , 'HERRERO', 'EXCELENTE');
INSERT INTO oficioempleado VALUES ('DIAZ JIMENEZ' , 'HERRERO', 'EXCELENTE');
INSERT INTO oficioempleado VALUES ('EZQUERRO TOME' , 'LEÑADOR', 'BUENO');
INSERT INTO oficioempleado VALUES ('GONZALEZ ORBEA' , 'HERRERO', 'PRECISO');
INSERT INTO oficioempleado VALUES ('PEREZ LOPEZ' , 'CONDUCTOR', 'RAPIDO');
INSERT INTO oficioempleado VALUES ('VAZQUEZ LOPEZ' , 'LABRADOR', 'LENTO');
INSERT INTO oficioempleado VALUES ('GONZALEZ LOPEZ' , 'HERRERO', 'EXCELENTE');
INSERT INTO oficioempleado VALUES ('JUAREZ NORIEGA' , 'CONDUCTOR', 'EXCELENTE');
INSERT INTO oficioempleado VALUES ('TEJERINA RUIZ' , 'LEÑADOR', 'BUENO');
INSERT INTO oficioempleado VALUES ('ALVAREZ RODRIGUEZ' , 'CONDUCTOR', 'RAPIDO');
INSERT INTO oficioempleado VALUES ('DONOSO ANTON' , 'HERRERO', 'PRECISO');
INSERT INTO oficioempleado VALUES ('EGUIBAR PUENTE' , 'LABRADOR', 'LENTO');
INSERT INTO oficioempleado VALUES ('GOMEZ ORDUÑA' , 'HERRERO', 'EXCELENTE');
INSERT INTO oficioempleado VALUES ('PAVON LOPEZ' , 'CONDUCTOR', 'EXCELENTE');
INSERT INTO oficioempleado VALUES ('PANADERO JUAN' , 'PICADOR', 'EXCELENTE');


























